// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdchdalpqpiqkmiatlmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkY2hkYWxwcXBpcWttaWF0bG12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4OTUzODcsImV4cCI6MjA1OTQ3MTM4N30.HkPj1iYNGxkJJ64_3yw3lhIV3omJ2eyYuzd0Viu3ixQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);